### ISSUE TITLE
@ngrx/component roadmap

### ISSUE THREAD

**Issue by BioPhoton** [ngrx/platform#2441]
# @ngrx/component roadmap

## Vision
My personal BIG vision, that IMHO fits very well with this project, is:
> Write fully reactive Angular applications without using the word `subscribe` or `unsubscribe` a single time.

## Nightly's
General code quality and tests. Documentation as well as examples.

**General Docs**
- [x] Add docs overview #2442

**Core**
- [x] cdAware creation factory #2443 #2473
  - [x] Ensure that it is in line with the current project

**Push Pipe**
  - [x] Ensure typing in the template

**Let Directive**
  - [ ] Ensure typing in the template
    - [x] `let` syntax
    - [ ] `as` syntax **help needed**

**Coalescing Features**
- [x] Implement strategy pattern in CdAware object #2458 #2473
- [x] ~Implement strategy performance features~
- [ ] ngrx/component add schematics #2450 #2452

## Alpha Release
- [x] [Design Doc - Push Pipe](https://hackmd.io/Uus0vFu3RmWRVGgmtzuUWQ?edit) In: HackMd, Michael Hladky.
- [x] [Design Doc - Let Directive](https://hackmd.io/8_3rp0A7RweSYJiulsifbQ?edit) In: HackMd, Michael Hladky.
- ~[ ] [Design Doc - Coalescing of Change Detection](https://hackmd.io/42oAMrzYReizA65AwQ7ZlQ) In: HackMd, Michael Hladky.~

## Beta Releases

- [ ] Finalize feature set

## To Discuss
- [Design Doc - ComponentStore Service](https://hackmd.io/zLKrFIadTMS2T6zCYGyHew?view) In: HackMd, Alex Okrushko.
- ~[Design Doc - Reactive Component State](https://hackmd.io/wVkWRc3XQWmtM6YcktRTrA) In: HackMd, Michael Hladky.~

**Comment by mfabioe** [comment]
can't wait to use it! seems promising! would solve a lot of problems with ngIf
