### ISSUE TITLE
@ngrc/component Refactor cdAware factory

### ISSUE THREAD

**Issue by BioPhoton** [ngrx/platform#2443]
Make sure it is aligned with the current way of creating factories. 
It would be good to consult @alex-okrushko for detailed requirements.

**Todo**

-  [ ] Refactored out things related to ngZone or optimizations in Ivy 
   - [ ] Change pipe config argument to a string
  - [ ] Adopt pipe and let
- [ ] Updte tests
  - [ ] Remove ivy and zone related tests

Related: #2441

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by BioPhoton** [comment]
Hi @alex-okrushko 

please have a look at #2458. If this incorporates all your wished I would be working directly on that and we could close both. 

Thanks for you time!
