### ISSUE TITLE
@ngrx/component implement generateFrames observable projection function

### ISSUE THREAD

**Issue by BioPhoton** [ngrx/platform#2446]
# Problem 

**See demo [here](https://stackblitz.com/edit/ng-zone-af-tests)**

For the coalesce operator we use the animationFrame as durationSelector. 
RxJS in v7 provides an observable projection function called `animationFrames` that would solve the problem. However, Angular uses zone.js and zone.js patchen all async functions in the browser.

We needed to create an observable same as `animationFrames` form the unpatched `requestAnimationFrame` in an Angular project.

# Solution
This is the reason we need to create an observable projection function generic enough to take all kind of async producers from the browser.

**Signature:** 
```typescript
export function generateFrames(
  asyncProducer: asyncProducerFn,
  asyncCanceler: asyncCancelerFn,
  timestampProvider: TimestampProvider = Date
): Observable<number>;
```
**Usage:** 

```typescript
import { generateFrames } from '@ngrx/component';

const afUnpatched$ =  generateFrames(
  window.__zone_symbol__requestAnimationFrame,
  window.__zone_symbol__cancelAnimationFrame
);
```
**Todos:**
- [x] Implement default implementation based on RxJS animationFrames projection function
- [x] Implement configurable interval source
- [x] Implement tests for aditional logic
- [x] Create docs
  - [x] Ensure linking in TOCs

Related: #2441

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by BioPhoton** [comment]
Docs Draft:

# generateFrames

Observable creation functions helpful in environments with patched global APIs like zone.js environments.

## Description 

Like `animationFrames` this function returns an observable emitting the passed milliseconds with every animationFrame starting from the moment of subscription.
In comparison to `animationFrames`, `generateFrames` is more generic and is able to take `animationFrame`, `setInterval`, `setTimeout` PromiseLike things, etc.

This is especially helpful in environments where global APIs are patched by libraries like zone.js. 
Using this operator can ensure we use an unpatched version of the API.

## Signature
```typescript
export function generateFrames(
  asyncProducer: asyncProducerFn,
  asyncCanceler: asyncCancelerFn,
  timestampProvider: TimestampProvider = Date
): Observable<number>;
```
## Usage

```typescript
import { Observable} from 'rxjs';
import { generateFrames } from '@ngrx/component';

const afUnpatched$: Observable<number> =  generateFrames(
  window.__zone_symbol__requestAnimationFrame,
  window.__zone_symbol__cancelAnimationFrame
);
```

**Comment by BioPhoton** [comment]
closed because of https://github.com/ngrx/platform/pull/2473#discussion_r409032031
