### ISSUE TITLE
@ngrx/component implement coalesce observable operator function

### ISSUE THREAD

**Issue by BioPhoton** [ngrx/platform#2448]
# Problem 

**See demo [here](https://stackblitz.com/edit/ng-af-coalescing-tests)**

Multiple emissions of different observables at the same time as well as values from the same observable emitted synchronously trigger rendering too often.

```typescript
range(1,5)
.subscribe(update => renderView());
// 5 times

// ====

of(1)
.subscribe(update => renderView());
of(2)
.subscribe(update => renderView());
// 2 times
```

What we need is an extended version of the throttle operator.

For the coalesce we need an adopted version of throttle that:
- allows trailing true
- allows context scoping 
 
# Solution
This is the reason we need to create an observable operator function generic enough to take all kind of durationSelectors, and scopes in addition to the throttle operator.

**Signature:** 
```typescript
export function coalesce<T>(durationSelector, config): MonoTypeOperatorFunction<T>;
```
**Basic Usage:** 

```typescript

import { coalesce, generateFrames } from '@ngrx/component';

range(1,5)
.pipe(coalesce())
.subscribe(state => renderView());
// 1 time
```
**Usage in Angular:** 

```typescript

import { coalesce, generateFrames } from '@ngrx/component';

const afUnpatched$ =  generateFrames(
  window.__zone_symbol__requestAnimationFrame,
  window.__zone_symbol__cancelAnimationFrame
);

const cfg = {context: this};

range(1,5)
.pipe(coalesce(() => afUnpatched$, cfg))
.subscribe(state => renderView());

range(1,5)
.pipe(coalesce(() => afUnpatched$, cfg))
.subscribe(state => renderView());

// 1 time
```

**Todos:**
- [x] Add basic tests for coalesce operator from throttle operator
- [x] Add throttle based logic for the coalesce operator
- [x] Fix inconsistent leading true implementation and tests
- [x] Extend config and set leading to false and trailing to true
- [x] Implement tests for durationSelector
  - [x] The config defaults
  - [x] The new behavior
- [x] Implement generateFrames Observable projection function to enable using unpatched animatinFrame
- [x] Implement default throttle durationSelector based on the browsers AnimationFrame. Use `generateFrames`
- [x] Implement additional logic if needed to pass tests
- [x] Implement isCoalescing as symbol for save usage
- [x] add scoping:
  - [x] by subscription
  - [x] by any passed object
- [x] Implement tests for scoping:
  - [x] The config defaults
  - [x] The new behavior
- [x] Create docs

---

Updates:
- [x] Use TestScheduler directly in the unit tests 
- [x] Implement the coalescing flag as WeakMap see: https://github.com/phenomnomnominal/tsquery/pull/34
      **NOTICE:** [WeakMaps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) don't hold hard references, so garbage collection will happen. 
  - [x] Write tests that show that the current implementation mutates the passed context object.
        Use `Reflect.ownKeys` to test it as respects also Symbol keys.
  - [x] Implement a version of a WeakMap that maintains a generic set of properties as a creation function.
  - [x] Implement tests for the `createPropertiesWeakMap` function
  - [x] Implement the WeakMap in the operator and remove the symbol logic
  - [x] Implement tests that ensure that the passed context object is not mutated 

Related: #2441

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by BioPhoton** [comment]
Reason see discussion in #2456
