### ISSUE TITLE
@ngrx/component add schematics

### ISSUE THREAD

**Issue by BioPhoton** [ngrx/platform#2450]
## ngrx/components schematics
Implement schematics and migration scripts for the new features of ngrx/component.

Related: #2441 

**Todos**
- [x] Implement schematics
  - [x] ng add @ngrx/components
- [x] Implement migration scripts
   - [x] factor-rule to replace `async` with `ngrxPush` see [angular/material example](https://github.com/angular/components/blob/master/src/material/schematics/ng-update/upgrade-rules/misc-ripples-v7/ripple-speed-factor-rule.ts)
  - [ ] factor-rule to replace `*ngIf="value$ | async as value"` with `*ngrxLet="value$; let value"` **(TO EVALUATE)**
- [ ] Implement tests
  - [ ] **TODO** checkout how current tests are done
- [ ] Docs
  - [ ] Update [dependencies](https://ngrx.io/guide/schematics#dependencies)
  - [ ] Update [migration](https://ngrx.io/guide/migration/v9)

## If accepted, I would be willing to submit a PR for this feature

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment]
Fixed via #2611
